// ============================================================
// SMC-DATA.JS — Smart Money Concepts Knowledge Base
// SMC Suite
// Verified & expanded against NZT Trader Mentorship notes (149pg source)
// ============================================================

const SMC_DATA = {

  // ── SESSIONS & KILLZONES ──────────────────────────────────
  // CORRECTED: NZT's notes do not define separate "Silver Bullet" time
  // windows the way ICT does. In NZT's material, "silver bullet" refers
  // specifically to the second-leg retracement entry inside a Market
  // Maker Model (see market_maker_models concept) — not a standalone
  // clock window. The killzone times below are confirmed directly in
  // the notes (LOKZ, NYOKZ, CBDR). The old 03:00-04:00 / 10:00-11:00 /
  // 14:00-15:00 "silver bullet" sub-windows have been removed since
  // they are not sourced from NZT's material.
  sessions: {
    asian: {
      name: 'Asian Session',
      ny_time: '20:00 – 00:00 NY',
      role: 'Range formation. NZT watches whether Asia consolidates or expands — this dictates London\'s expected role.',
      killzone: false,
      characteristics: [
        'General Rule: whatever the previous session did NOT do, the next session is likely to do',
        'If Asia consolidates → London likely executes a Judas Swing (expansion)',
        'If Asia expands → London likely consolidates',
        'Asian Range under 40 pips is favorable for a clean London Judas Swing the next session',
        'Asian Range over 40 pips, or trending (steady incline/decline) rather than sideways → avoid London',
        'You want to see the Asian Range low (or high) swept during London for a valid Judas Swing',
      ],
      probability: 'Low — range formation only, sets the stage',
      color: '#4a9eff',
    },
    london: {
      name: 'London Session (LOKZ)',
      ny_time: '02:00 – 05:00 NY',
      role: 'The London Open Kill Zone (LOKZ). Preferred role is the Judas Swing — price moves against bias first to grab liquidity below/above the NY Midnight Open before the real move.',
      killzone: { start_ny: '02:00', end_ny: '05:00', label: 'London Open Killzone (LOKZ)' },
      characteristics: [
        'NY Midnight Opening Price is the true overbought/oversold reference for London',
        'Want to see price swing below/above the Midnight Open — a run on liquidity is expected',
        'Liquidity targets for the Judas Swing: previous 4H high/low, previous day high/low, or an HTF PD-Array',
        'London Lunch (05:00–07:00 NY): avoid trading — dead zone between sessions',
        'London often places the weekly high or low on Monday/Tuesday (bearish week: high; bullish week: low)',
        'CBDR (14:00–20:00 NY prior day) protraction is measured to estimate how far the Judas Swing will extend',
        'If London consumes most of the ADR, NY is likely to consolidate — if London leaves ADR on the table, NY can continue or reverse',
      ],
      probability: 'High — primary session for the day\'s manipulation/Judas Swing',
      color: '#40e0d0',
    },
    newyork_am: {
      name: 'New York Session (NYOKZ)',
      ny_time: '07:00 – 10:00 NY',
      role: 'The New York Open Kill Zone. Role depends entirely on where London left price relative to the PDA Matrix: continue London\'s move, or reverse it.',
      killzone: { start_ny: '07:00', end_ny: '10:00', label: 'New York Open Killzone (NYOKZ)' },
      characteristics: [
        'Continuation: if London traded into a Discount PDA and began rejecting near the end of the session, expect a short NY retracement (Judas-like protraction) before continuation',
        'This NY protraction is typically hunted around 08:30 NY time — window roughly 08:15–08:45',
        'Reversal: if London traded deep into a Premium PDA and rejected off it within the London session, expect NY to continue that rejection (opposite direction)',
        'Key framing rule: if London targeted and rejected a significant HTF PDA, NY is expected to continue that resultant move',
        'Do not trade NY in isolation — the entire NY plan hinges on what London did first',
        'London-to-NY OTE is one of NZT\'s favorite and most repeatable setups',
      ],
      probability: 'Highest — primary execution window of the day',
      color: '#ff0080',
    },
    newyork_lunch: {
      name: 'New York Lunch',
      ny_time: '12:00 – 13:00 NY',
      role: 'Dead zone. Institutional participation drops sharply.',
      killzone: false,
      characteristics: [
        'Avoid all entries',
        'Price often ranges or partially reverses the AM session move',
        'Low volume produces false signals',
        'Use this time to review the day\'s PDA reactions and plan for the PM window',
      ],
      probability: 'Very low — avoid',
      color: '#ffaa00',
    },
    newyork_pm: {
      name: 'New York PM / London Close',
      ny_time: '13:00 – 17:00 NY',
      role: 'Secondary window. The London Close Kill Zone is where smart money frequently books profit — expect position closing, not necessarily new directional pushes.',
      killzone: { start_ny: '13:00', end_ny: '17:00', label: 'NY PM / London Close Window' },
      characteristics: [
        'London Close KZ is often profit-taking territory rather than a fresh expansion window',
        'Continuation of the AM session bias is the most common outcome',
        'Lower volume than AM — widen stops or reduce size accordingly',
        'Arrays formed during the London Open tend to be more respected in NY than arrays formed during London Lunch',
      ],
      probability: 'Moderate — secondary/closing window',
      color: '#9b59ff',
    },
  },

  // ── WEEKLY BIAS PROBABILITIES ─────────────────────────────
  weekly_bias: {
    bearish: {
      weekly_high_monday: 0.40,
      weekly_high_tuesday: 0.40,
      combined_mon_tue: 0.80,
      description: 'In a bearish week, the weekly high is commonly made Monday or Tuesday. Thursday often caps the low of the week; Friday is frequently a reversal day retracing back into the weekly range.',
    },
    bullish: {
      weekly_low_monday: 0.40,
      weekly_low_tuesday: 0.40,
      combined_mon_tue: 0.80,
      description: 'In a bullish week, the low of the week is commonly made Monday or Tuesday. Thursday often caps the high of the week; Friday frequently retraces back into range after a large Thursday move.',
    },
    note: 'Sunday\'s Opening Price (5PM NY time) is the weekly equivalent of the Midnight Opening Price — use it to profile the week the same way the Midnight Open profiles the day.',
  },

  // ── REFERENCE LEVELS ─────────────────────────────────────
  reference_levels: {
    nwo: { name: 'New Week Open (Sunday Open)', description: 'Sunday 5PM NY open. The weekly equivalent of the Midnight Opening Price — anticipate manipulation early week (Mon/Tue) beneath/above it, then expansion through the rest of the week.', timeframe: 'Weekly' },
    nmo: { name: 'New Month Open', description: 'Opening price of the new month. NZT gives most respect to the monthly candle in the first two weeks of the month — this is typically when the monthly Judas Swing is placed.', timeframe: 'Monthly' },
    nqo: { name: 'Quarterly Open (NZT Quarters)', description: 'NZT\'s quarters differ from the standard financial year: Q1 begins Dec 1, Q2 begins Mar 1, Q3 begins Jun 1, Q4 begins Sep 1. A significant directional move typically occurs at the start of most quarters, with a retracement around the middle.', timeframe: 'Quarterly' },
    midnight_open: { name: 'Midnight Open (NY 00:00)', description: 'The single most important intraday reference. Everything below it is protraction/manipulation (in a bullish day); everything above it is expansion. Draw it on every LTF chart. Never buy above it if bearish; never sell below it if bullish.', timeframe: 'Daily' },
    asia_high: { name: 'Asian High', description: 'Highest point of the Asian range (20:00–00:00 NY). Buy-side liquidity above it. London targets this first if Asia consolidated.', timeframe: 'Daily' },
    asia_low: { name: 'Asian Low', description: 'Lowest point of the Asian range. Sell-side liquidity below it. London targets this first if Asia consolidated.', timeframe: 'Daily' },
  },

  // ── CORE CONCEPTS ─────────────────────────────────────────
  concepts: [

    {
      id: 'market_structure',
      name: 'Market Structure',
      category: 'Foundation',
      icon: '📊',
      status: 'built',
      description: 'The backbone of all analysis. Price moves in structured sequences of highs and lows. The market runs on a price delivery algorithm with two jobs: seeking liquidity (buyside↔sellside) and rebalancing imbalances.',
      rules: [
        'Bullish structure: series of Higher Highs (HH) and Higher Lows (HL)',
        'Bearish structure: series of Lower Highs (LH) and Lower Lows (LL)',
        'CORRECTED: prioritize candle BODIES over wicks. Wicks are manipulation; bodies represent institutional intent. A wick above an old high is NOT a Break of Structure — you need a body close beyond it',
        'A high is defined by a three-candle formation where the middle candle\'s high exceeds both neighbors; a low is the mirror (middle candle\'s low is below both neighbors)',
        'Break of Structure (BOS): price closes beyond a swing point in the direction of the existing trend — continuation',
        'Market Structure Shift (MSS): a change in the state of price delivery. It is fractal — happens on every timeframe, weekly down to 1-minute',
        'An MSS does NOT automatically dictate a long-term bullish/bearish bias on its own — it must occur in proper context (after a liquidity sweep or PD Array interaction) to be meaningful',
        'Every single time a new low/high is made, the range changes — take the most obvious high and most obvious low',
        'Always read structure top-down: monthly → weekly → daily → 4H → 1H → 15M',
      ],
      visual_type: 'annotated_chart',
      key_levels: ['swing_high', 'swing_low', 'BOS_level', 'MSS_level'],
      related: ['liquidity', 'order_blocks', 'top_down', 'draw_on_liquidity'],
    },

    {
      id: 'liquidity',
      name: 'Liquidity',
      category: 'Foundation',
      icon: '💧',
      status: 'built',
      description: 'The market runs on liquidity. Liquidity is where you find the most buy and sell orders. Above old highs = buyside liquidity (sell-stop orders sit there for institutions to fill against). Below old lows = sellside liquidity.',
      rules: [
        'Buy-side liquidity (BSL) sits above swing highs and equal highs — these are retail buy-stops/breakout orders',
        'Sell-side liquidity (SSL) sits below swing lows and equal lows — retail sell-stops/breakout orders',
        'In a bearish market, price often first sweeps BSL (above old highs) to fuel the move down, then targets SSL as the real objective',
        'In a bullish market, price often first sweeps SSL (below old lows) to accumulate, then targets BSL',
        'Retail breakout traders place orders above resistance / below support — these become the liquidity institutions harvest',
        'Equal highs/lows do not have to be perfectly equal — "equal enough" for retail traders to treat as support/resistance is enough to generate a liquidity pool',
        'Relative equal highs/lows act as a magnet — the algorithm treats them as a high-probability Draw on Liquidity target',
        'A liquidity grab without a structural shift is just a wick — wait for MSS + displacement confirmation before treating it as meaningful',
      ],
      visual_type: 'annotated_chart',
      related: ['market_structure', 'order_blocks', 'fvg', 'draw_on_liquidity', 'turtle_soup'],
    },

    {
      id: 'draw_on_liquidity',
      name: 'Draw on Liquidity (DOL)',
      category: 'Foundation',
      icon: '🧲',
      status: 'built',
      description: '"There should be a bigger focus on DOL." — one of NZT\'s most repeated MAJOR GEMs. Before outlining PD Arrays, outline the Draw on Liquidity first. A common mistake is overemphasizing PD Arrays and underemphasizing DOL — the order should be: 1) Draw on Liquidity, 2) PD Arrays. NOTE — treat this as a PREREQUISITE, not a standalone idea: every other concept in this suite (Market Structure, PD Array Matrix, Market Maker Models, Top-Down Analysis, DSE/CISOD) is only meaningful once the DOL has been identified first. Do not evaluate an entry array in isolation from it.',
      rules: [
        'DOL is the ultimate objective — the liquidity pool or imbalance price is being engineered toward',
        'Every trade starts with three questions: Where is price? Where did it come from? Where is it likely to go (DOL)?',
        'Once you know the DOL, the arrays on the PDA Matrix are simply the tools used to frame how you attack it',
        'When price gets into your price arrays or runs a key level (weekly/daily high or low), that is when you start framing the trade idea — hunting for MMXM, MSS, displacement',
        'Intraday trades should be aligned with the DOL and held until the liquidity is reached — it is okay to hold a trade over the day if the DOL hasn\'t been met',
        'Previous weekly/daily highs and lows are key reversal points to frame your DOL around',
        'Stay away from a "seek and destroy" market — where both buyside and sellside liquidity get taken with no clear DOL. Stand aside here',
        'When external liquidity is cleared, immediately reframe your DOL toward the internal liquidity now being aimed for (see External vs Internal Range Liquidity) — the DOL is not static, it updates as each level is cleared',
        'Practical workflow: identify DOL → identify which PD Array frames the attack on it → identify the Stage/CISOD confirming the move → THEN execute the entry. DOL is step one in every single trade, without exception',
      ],
      visual_type: undefined,
      related: ['liquidity', 'market_structure', 'pd_array_matrix', 'external_internal_liquidity', 'dse_cisod', 'top_down'],
    },

    {
      id: 'premium_discount',
      name: 'Premium & Discount',
      category: 'Foundation',
      icon: '⚖️',
      status: 'built',
      description: 'Buy at discount, sell at premium — the 50% (equilibrium) Fibonacci level divides a range into the two zones. This is the equilibrium filter for every entry. Always paired with the Draw on Liquidity: the DOL tells you WHERE price is going; premium/discount tells you WHERE to align your entry relative to that destination.',
      rules: [
        'You want to be a buyer underneath the 50% level (discount); a seller above it (premium)',
        'Take the most obvious external range high/low to define the 50% — every new high/low made changes the range',
        'Be aware the algorithm can easily reject the 50% level — don\'t hold trades right at equilibrium, sentiment is likely to shift there',
        'When external range and internal range premium/discount align, probabilities increase — directional confluence (see External vs Internal Range Liquidity)',
        'When a swing low is made in a bullish narrative into a discount combined with an FVG, and price displaces away, target the next DOL higher — premium/discount is never evaluated in isolation from the DOL',
        'Never buy in premium; never sell in discount — this is a hard rule repeated throughout the notes',
        'At fair value (equilibrium) price is usually choppy and shows resistance — don\'t hold trades there',
      ],
      visual_type: undefined,
      related: ['pd_array_matrix', 'ote', 'market_maker_models', 'external_internal_liquidity', 'draw_on_liquidity'],
    },

    {
      id: 'external_internal_liquidity',
      name: 'External vs Internal Range Liquidity',
      category: 'Foundation',
      icon: '🔁',
      status: 'built',
      description: 'A distinct layer beneath premium/discount, not a restatement of it: matching WHICH liquidity — the range boundary (external) or the liquidity resting inside it (internal) — you are targeting, and whether both agree on premium/discount status. This is the mechanism that connects Draw on Liquidity to the PD Array Matrix.',
      rules: [
        'External Range Liquidity (ERL): the old high/low that defines the outer boundary of the current dealing range. This is your reference point for the price arrays and is typically what gets swept/cleared first',
        'Internal Range Liquidity (IRL): the liquidity and imbalances resting inside that range — minor equal highs/lows, FVGs, order blocks. This contains the next likely order fill once ERL is cleared',
        'Repeatable sequence: price action usually clears external liquidity first, then retraces back into the internal range before the real expansion begins',
        'When external liquidity is taken out, immediately reframe: look into the internal liquidity and identify what internal liquidity is now being aimed for — this becomes the new near-term DOL',
        'Directional confluence check: when the external range and internal range agree on premium/discount status (both premium or both discount), probabilities increase — this is a required alignment check, not optional',
        'Whenever an external range is broken, a new range is made — new high, new low, new PDA Matrix, new PD Arrays. Re-run your analysis from scratch rather than forcing the old range to still apply',
        'Always identify the current price range you are working in before anything else — described directly in the notes as a GEM-level habit',
      ],
      visual_type: undefined,
      related: ['premium_discount', 'pd_array_matrix', 'draw_on_liquidity', 'liquidity'],
    },

    {
      id: 'pd_array_matrix',
      name: 'PD Array Matrix',
      category: 'Entry Arrays',
      icon: '🗂️',
      status: 'built',
      description: '"The PD Array Matrix is the backbone of your trading." Price arrays exist in a defined order radiating out from equilibrium. Not every array has to exist within the Matrix — if one is absent, move to the next. The Matrix is the TOOL; the Draw on Liquidity is the OBJECTIVE — always identify the DOL before framing which array in the Matrix you are trading off.',
      rules: [
        'Order from equilibrium outward (premium side): Equilibrium → +ve Mitigation Block → +ve Breaker Block → Liquidity Void → Fair Value Gap → +ve Order Block → Rejection Block → Old High',
        'Mirror order on the discount side: Equilibrium → -ve Mitigation Block → -ve Breaker Block → Liquidity Void → Fair Value Gap → -ve Order Block → Rejection Block → Old Low',
        'Higher timeframe arrays highlight key price targets — identify high-probability institutional levels for entries, exits, and direction',
        'The external range is your reference point for the price arrays; the internal range contains the next likely order fill (see External vs Internal Range Liquidity)',
        'Do not consider entering off a PD Array if it goes against your narrative — wait to see how the market reacts off it first',
        'Do not "scale down" and replace HTF PD Arrays with LTF ones — monitor HTF arrays on your lower timeframes, but the HTF zone is the reference',
        'When a price array overlaps with a dealing range level (.00, .20, .50, .80 — the "20-figure concept"), that increases the probability price is drawn there',
        'Sequence discipline: identify the Draw on Liquidity first, THEN select which array on the Matrix frames your attack on it — never the other way around',
      ],
      visual_type: undefined,
      related: ['premium_discount', 'draw_on_liquidity', 'external_internal_liquidity', 'order_blocks', 'fvg'],
    },

    {
      id: 'fvg',
      name: 'Fair Value Gaps (FVG)',
      category: 'Entry Arrays',
      icon: '⚡',
      status: 'built',
      description: 'A three-candle sequence resulting from an aggressive one-directional move. The gap is defined wick-to-wick — the empty space where the wicks of candle 1 and candle 3 do not overlap the middle candle.',
      rules: [
        'Bullish FVG: gap between the high of candle 1 and the low of candle 3 (candle 2 is the impulse up)',
        'Bearish FVG: gap between the low of candle 1 and the high of candle 3 (candle 2 is the impulse down)',
        'CORRECTED: imbalances are defined wick-to-wick, not body-to-body — reconfirmed directly from notes',
        'Price does not have to fill the entire FVG — it may only tap the edge of the defining candle before resuming direction',
        'Imbalances typically fill at 50% of the candle/gap — use this as your standard entry reference point',
        'Define FVGs on the 4H or 1H timeframe for HTF reference, then find entries on lower timeframes',
        'Old FVGs become new FVGs — an FVG left unfilled remains a valid reference point far into the future (within roughly a 60-day lookback)',
        'Re-delivered rebalance: if a candle\'s wick is immediately traded through by the following candle\'s body, disregard that wick when identifying the imbalance — it is not considered "delivered" price action until rebalanced by opposing order flow',
        'FVG + Order Block confluence = high probability entry ("pair all PD Arrays with FVGs")',
        'When an imbalance fills an imbalance, that creates a "balanced price range" — the two nullify each other and are not expected to be traded back into',
      ],
      visual_type: 'annotated_chart',
      related: ['order_blocks', 'liquidity', 'ote', 'liquidity_void'],
    },

    {
      id: 'liquidity_void',
      name: 'Liquidity Void',
      category: 'Entry Arrays',
      icon: '🌀',
      status: 'built',
      description: 'A range/candle where price moved aggressively in one direction without leaving wicks — an absence of opposing orders. Distinct from an FVG, though the two are closely related and often paired.',
      rules: [
        'A liquidity void is essentially a candle (or run of candles) that moves one way without leaving wicks — no two-sided trading occurred',
        'The void sits within the PD Array Matrix between the breaker/mitigation block and the Fair Value Gap',
        'Voids need to be rebalanced the same way imbalances do — price is drawn back to them over time',
        'Combine voids with other PD Arrays for higher probability rather than trading them in isolation',
      ],
      visual_type: undefined,
      related: ['fvg', 'pd_array_matrix'],
    },

    {
      id: 'order_blocks',
      name: 'Order Blocks',
      category: 'Entry Arrays',
      icon: '🧱',
      status: 'built',
      description: 'The last opposing candle before a strong, defining move away (Displacement). Represents where institutional orders were likely entered. The validity of an OB is confirmed by Displacement, not by time.',
      rules: [
        'Bullish OB: the lowest down-close candle before bullish displacement',
        'Bearish OB: the highest up-close candle before bearish displacement',
        'An Order Block is a change in the state of price delivery — a retracing candle will reject from it',
        'If the candles preceding a single-candle OB were consecutive in the same direction, that whole run can represent multiple OB candles on a lower timeframe',
        'REDEFINED (major correction): a down-close candle at a key reversal level (HTF FVG rebalance or macro liquidity sweep), followed by displacement that engulfs the candle body, immediately becomes an institutional Order Block — you do NOT need to wait for a distant structural break to validate it',
        'Breaker block: formed when a low is broken, a higher high forms, then price crashes back through the initial low — the breaker is the lowest down-close candle in that sequence',
        'Mitigation block: identified following an MSS — an area containing trapped buyers/sellers that price returns to before continuing',
        'Reclaimed Order Block: represents hedged positions from the opposing side of a Market Maker curve — see Market Maker Models',
        'Difference between mitigation and breaker: a breaker goes higher-high-then-lower-low; a mitigation block does not require that sequence',
        'Make sure OBs are in line with your bias — an OB is invalidated when price closes through the entire body',
      ],
      visual_type: 'annotated_chart',
      related: ['fvg', 'liquidity', 'market_structure', 'ote', 'breaker_mitigation', 'market_maker_models'],
    },

    {
      id: 'breaker_mitigation',
      name: 'Breaker & Mitigation Blocks',
      category: 'Entry Arrays',
      icon: '🔀',
      status: 'built',
      description: 'The breaker block is responsible for and comes BEFORE the MSS. You trade the breaker when you see the MSS confirm it. No breaker = no reversal — this is a hard rule.',
      rules: [
        'Bearish breaker: High → Low → Higher High → Lower Low. The breaker is the lowest down-close candle in the low between the two highs',
        'You cannot have an MSS without a breaker block — the algorithm uses the breaker as the reference point for where offside large-fund traders can mitigate before continuing with the shift',
        'Requires a CLEAN break of the low/high — a choppy break is not a valid breaker trade',
        'Only take a breaker trade if it confirms the HTF bias (1H and above). Low-timeframe breakers that oppose the major trend are unreliable',
        'Do entries on the lower timeframes — look for an MSS on the LTF inside the HTF breaker signal',
        'If there is an imbalance left as well as a breaker block during an MSS, place the stop loss above (or below) the imbalance',
        'Mitigation block: contains trapped buyers/sellers following an MSS. Price action inside it remains dynamic — it may still contain its own OBs, imbalances or voids that need addressing',
        'You can trade mitigation blocks down to wherever price meets a point it can stall — order block, imbalance, or other PD Array. One of the most repetitive patterns you\'ll find daily',
      ],
      visual_type: undefined,
      related: ['order_blocks', 'market_structure', 'draw_on_liquidity'],
    },

    {
      id: 'rejection_blocks',
      name: 'Rejection Blocks',
      category: 'Entry Arrays',
      icon: '↩️',
      status: 'built',
      description: 'Found only on swing highs/lows. When there is more wick than body, it is usually a rejection block — the zone is defined by the wick, not the body. NZT\'s favorite setup to trade, especially when it reacts off an older HTF PD Array or a former run on liquidity.',
      rules: [
        'The rejection candle is the highest (or lowest) CLOSE candle before the move away — doesn\'t matter if it\'s an up or down candle',
        'A rejection block is usually an order block when viewed on a lower timeframe',
        'When taking profit, consider rejection blocks as resistance — take profit there rather than trying to break through and risk your gains',
        'The best rejection blocks are those off an older HTF PD Array or a former run on liquidity — always cut to the left of the chart',
      ],
      visual_type: undefined,
      related: ['order_blocks', 'liquidity'],
    },

    {
      id: 'ote',
      name: 'Optimal Trade Entry (OTE)',
      category: 'Entry Arrays',
      icon: '🎯',
      status: 'built',
      description: 'Defined by the Fibonacci retracement tool. The OTE zone is the area between the 0.62 and 1.0 retracement levels, used to identify premium/discount within a range for a precision entry.',
      rules: [
        'Use the most obvious swing point when anchoring your Fib',
        'High-probability trade: an OTE that overlaps with an FVG or other imbalance',
        'Be careful anchoring fibs from swings where an open FVG rests just before it — you\'ll likely get stopped out by an IOFED into that FVG first',
        'London-to-NY OTE is one of NZT\'s favorite and most repeatable setups — London usually begins the SMR/Judas, NY provides the retracement entry into OTE',
        'OTE on the week\'s low/high after a displacement away from it is another favorite setup',
        'Don\'t get too locked up on the exact OTE numbers — smart money often eats through shorts fast after entering premium beyond 50%',
        'Consider entering ahead of the OTE region if there\'s a reason price is unlikely to reach it (e.g. an FVG resting right at the 50% mark of the OTE zone, or a breakaway gap before the region)',
      ],
      visual_type: undefined,
      related: ['premium_discount', 'fvg', 'order_blocks', 'market_maker_models'],
    },

    {
      id: 'market_maker_models',
      name: 'Market Maker Models (MMSM / MMBM)',
      category: 'Setups',
      icon: '🏦',
      status: 'built',
      description: 'The Market Maker Sell Model (MMSM) is a movement from discount to premium, then a reversal lower. Three components: the buy side of the curve, the Smart Money Reversal (SMR), and the sell side of the curve. (Market Maker Buy Model is the exact mirror.)',
      rules: [
        'Component 1 — Buy side of the curve: smart money hedges SHORT positions by buying into the market before premium is reached. This begins in a discounted area, starting with initial consolidation, and trades higher until premium is met',
        'The key to the buy side of the curve is identifying areas of re-accumulation — where smart money hedges, causing minor displacement',
        'Component 2 — Smart Money Reversal (SMR): where the buy side ends and the sell side begins. Anticipate the SMR at logical reversal points — rebalancing an imbalance inside a premium OB, or running significant buyside liquidity (previous week/day high)',
        'SMR is confirmed by waiting for displacement AWAY from the premium array where it is hunted — this displacement signals the momentum shift',
        'Component 3 — Sell side of the curve: once SMR is confirmed, the sell side is anticipated to deliver DOWN THROUGH the initial consolidation that started the buy side — that consolidation is the ultimate target',
        'Reclaimed Order Block: the bearish Reclaimed OB is the up-close candle before the minor displacement lower on the buy side of the curve — represents smart money\'s hedged positions. Frame retracement entries here to align with smart money (opposite for bullish)',
        'The "Silver Bullet" entry (ICT\'s term, adopted by NZT): the retracement entry after the second leg of distribution, following the low-risk sell/buy off the SMR — this is NZT\'s single favorite trade if he could only take one setup',
        'Never hunt reversals in "no man\'s land" — only at logical premium/discount PD Arrays, never at a bare 50% level with nothing to pair the reversal against',
        'A "three-leg drive" (series of upward thrusts with minor pullbacks) pushing directly into a Premium array is the trigger to anticipate a Market Maker Sell Model',
      ],
      visual_type: undefined,
      related: ['premium_discount', 'order_blocks', 'ote', 'draw_on_liquidity'],
    },

    {
      id: 'turtle_soup',
      name: 'Turtle Soup',
      category: 'Setups',
      icon: '🐢',
      status: 'built',
      description: 'NZT calls it "Turtle Neck" — a turtle\'s head goes slowly out of the shell and comes back fast. Price pokes above/below a key liquidity level, hits a PD Array, and immediately retracts back into range.',
      rules: [
        'Step 1 — Identify the "suspect" liquidity: a clean level where retail stops sit. Bearish: Previous Week High (PWH) or Previous Day High (PDH). Bullish: Previous Week Low (PWL) or Previous Day Low (PDL)',
        '"Flat" equal levels are more likely to be run than a single sharp wick',
        'Step 2 — Locate the PD Array: find an FVG or OB resting just beyond the liquidity pool — this is the rejection zone/ceiling or floor',
        'Step 3 — Monitor for the economic driver: Turtle Soups often trigger during high-impact (red folder) news — use Forex Factory to time entries',
        'Step 4 — Execution: aim to enter near the 50% level or full closure of the FVG to maximize R:R. Look for a sharp rejection at the array',
        'Step 5 — Stop loss goes where the setup is falsified — outside the HTF imbalance or beyond the high/low of the PD Array. If price fully trades through the FVG, the narrative is likely wrong',
        'Take profit at the opposite liquidity pool or an internal range imbalance',
        'A Turtle Soup is the one exception to the rule that candle highs/lows must stay respected after a PD Array reaction — it is the deliberate exception',
      ],
      visual_type: undefined,
      related: ['liquidity', 'pd_array_matrix', 'fvg'],
    },

    {
      id: 'iofed',
      name: 'IOFED (Institutional Order Flow Entry Drill)',
      category: 'Setups',
      icon: '🎯',
      status: 'built',
      description: 'One of NZT\'s favorite things to trade — his pick if he could only trade one model. When we sweep the low/high of a candle (1D, 4H, 1H) and finish/close/enter a PD Array and reject off it — OR sweep liquidity inside an FVG.',
      rules: [
        'IOFED = sweep liquidity + rebalance, which is fundamentally "the job of the algorithm" in a single repeatable pattern',
        'Be careful anchoring OTE fibs from swings with an open FVG resting just before them — you\'ll likely get stopped out by an IOFED filling that FVG first',
        'A high-grade swing point suitable for OTE anchoring is one created by a Turtle Soup stop-run, or a swing rejecting an array that supports your bias (an IOFED)',
      ],
      visual_type: undefined,
      related: ['fvg', 'pd_array_matrix', 'ote'],
    },

    {
      id: 'offset_accumulation_distribution',
      name: 'Offset Accumulation / Distribution',
      category: 'Setups',
      icon: '⚖️',
      status: 'built',
      description: 'Offset Distribution: a bearish framework where smart money\'s short positions are precisely paired and filled against the large volume of retail buy stops resting above highs. Offset Accumulation is the exact bullish mirror.',
      rules: [
        'To take a bearish setup: locate the counterparty — a sizable buyside liquidity pool, consistently resting above the Previous Day\'s High or Previous Week\'s High',
        'When price runs above that pool, do NOT immediately offset short — wait for confirmation via displacement that the run was used to fund the reversal, leaving an imbalance behind',
        'Once confirmed, wait for a retracement back to that displacement\'s imbalance to align your entry with the reversal',
        'For the reversal setup: frame it around the Previous Day/Week High and Low plus significant PDA Matrix levels — the run above the PWH is where you "sit on your hands" anticipating the sell model',
        'Intraday sequence example: London Open Kill Zone establishes the High of the Day via Offset Distribution confirmed by MSS + displacement → NY Open provides the OTE retracement entry',
        'Mirror everything for Offset Accumulation (bullish): counterparty is sellside liquidity below the Previous Day/Week Low',
      ],
      visual_type: undefined,
      related: ['liquidity', 'draw_on_liquidity', 'market_maker_models'],
    },

    {
      id: 'ohlc_olhc',
      name: 'OHLC / OLHC Candle Delivery',
      category: 'Price Delivery',
      icon: '📐',
      status: 'built',
      description: 'A dedicated framework (Chapter 6) for predicting the next candle\'s anatomy. Understanding this dictates the next candle\'s likely direction and shape, feeding directly into weekly/daily bias and intraday entries.',
      rules: [
        'OLHC (bullish delivery): Open → trades Lower (creating the low/wick) → expands Higher (creating the high/wick) → Closes above the open, near the high',
        'OHLC (bearish delivery): Open → trades Higher (creating the high/wick) → expands Lower (creating the low/wick) → Closes below the open, near the low',
        'OLHC signature (Offset Accumulation): a bearish candle sweeps into a discount array → next candle opens, trades lower sweeping the previous low, then reverses and closes bullish → anticipate the following candle to continue in OLHC format',
        'OHLC signature (Offset Distribution): a candle sweeps the previous high into a premium array → reverses and closes bearish → anticipate the next candle(s) to print in OHLC format',
        'Continuation rule (bullish/OLHC): the low of the previous candle should be respected; the high should be broken/targeted. Target: continue until a Premium Array, opposing array, or BSL target is met',
        'Continuation rule (bearish/OHLC): the high of the previous candle should be respected; the low should be broken. Exception: a high may be broken only to retrace and fill an imbalance before continuation resumes',
        'Power of Three blended with candle anatomy: OLHC → Accumulation (Asia/Midnight Open), Manipulation is the LOW (Asia/London KZ), Distribution is the expansion (rest of London + NY). OHLC is the same but Manipulation is the HIGH',
        'The Judas Swing is the move from the Midnight Open to the opposing end of the range — it IS the manipulation/protraction phase',
        'Backward-Testing Protocol to practice: hide future candles on Daily/Weekly, identify a Premium/Discount array price just traded into, find the sweep candle, PREDICT the delivery (bias + anatomy) before revealing the next candle, then check',
        'Guardrail — Consolidation Test: if price is stuck between Premium and Discount without a clear sweep signature, it is in a Liquidity Generation phase — mark it "SIT OUT"',
      ],
      visual_type: undefined,
      related: ['market_structure', 'draw_on_liquidity', 'pd_array_matrix'],
    },

    {
      id: 'sessions_killzones',
      name: 'Sessions & Killzones',
      category: 'Time',
      icon: '🕐',
      status: 'built',
      description: 'Price is not random — it follows a time-based delivery algorithm. "Time is even more important than price." Specific windows deliver significant highs/lows far more often than others.',
      rules: [
        'Asian Range (20:00–00:00 NY): range formation only. Under 40 pips = favorable for a clean next-session Judas Swing',
        'LOKZ — London Open Killzone (02:00–05:00 NY): primary Judas Swing / reversal window',
        'NYOKZ — New York Open Killzone (07:00–10:00 NY): primary continuation-or-reversal window, highest volume',
        'The 08:30 NY retracement is a specific, heavily emphasized window: hunt for a run on a level from 07:00–08:30, then expect expansion 08:30–10:00',
        'London Close Killzone: often where smart money takes profit — not necessarily a fresh push',
        'CBDR (14:00–20:00 NY, previous day): used to measure how far a Judas Swing will protract — must be under 40 pips (ideally near 30) to be reliable; over 40–50 pips, avoid trading London',
        'Time without a valid price array = no trade, regardless of setup quality. A price array without the right time window = wait for the window',
        'As long as your PD Arrays sit within roughly a 60-day lookback range, the algorithm can still reasonably trade back into them',
      ],
      visual_type: 'session_clock',
      related: ['market_structure', 'liquidity', 'top_down', 'cbdr_adr'],
    },

    {
      id: 'cbdr_adr',
      name: 'CBDR & ADR',
      category: 'Time',
      icon: '📏',
      status: 'built',
      description: 'CBDR (Central Bank Dealer Range) measures the likely protraction of the Judas Swing. ADR (Average Daily Range) is the "pie" of potential daily movement — you want your piece of that pie.',
      rules: [
        'CBDR window: 14:00–20:00 NY time (previous day\'s session)',
        'CBDR must be under 40 pips to be used reliably — ranges closer to 30 pips are preferred',
        'Project Standard Deviations (SD) from the CBDR to estimate where the protraction will end and the market will reverse/expand — do not project beyond 3 SD generally (4th SD only with a significant news driver)',
        'Monitor the 50% midpoint of each SD as an additional reaction level',
        'Rule for entry: line up the projected CBDR SD level with the NY Midnight Opening Price, a logical PD Array, and a specific run on liquidity — all three together',
        'ADR = 5-day average of (High − Low). It is a "pie": if London consumes most of it, NY has limited room; if ADR is split evenly, NY has good potential for continuation or reversal',
        'If the previous day\'s range was roughly 2x the ADR, avoid the next London session — an oversized expansion suggests consolidation is coming',
        'After three consecutive up (or down) days, avoid looking for Day 4 continuation — a retracement/consolidation is more likely (still contextual to HTF PD Arrays)',
      ],
      visual_type: undefined,
      related: ['sessions_killzones', 'liquidity'],
    },

    {
      id: 'top_down',
      name: 'Top-Down Analysis',
      category: 'Protocol',
      icon: '🔭',
      status: 'built',
      description: 'CORRECTED — direct quote from the notes: "NZT uses mainly the Weekly and Daily [for bias]. He gives respect to the monthly in the beginning and middle of the month. Execution on the 15/5 min chart." This is not an evenly-weighted 7-rung cascade — bias formation and execution are two distinct jobs assigned to two distinct, specific timeframe groups, with everything else acting as secondary confirmation between them.',
      rules: [
        'ANCHOR RULE: bias is formed on the Weekly and Daily — these are stated directly as the primary timeframes, not one option among many',
        'Monthly is checked for context, not for entries — most relevant in the beginning and middle of the month (this is when the monthly Judas Swing typically occurs)',
        'Execution happens on the 15M or 5M chart — stated directly as the entry timeframe, not inferred',
        '1H and above is the minimum threshold required to validate an HTF-level confirmation (e.g. a breaker block is only tradeable if it confirms a 1H+ bias)',
        'Your high-timeframe bias (minimum daily) MUST align with your low-timeframe direction — this is a hard requirement, not a preference',
        '"HTF point of interest, LTF for precise entries is key" — the HTF tells you the story of where the market is going; LTFs are only ever used for precise entry timing, never for forming the narrative',
        'Always determine the expected direction of the HTF candles (monthly and weekly) BEFORE forming a bias on the weekly/daily chart — the order of operations matters',
        'For developing traders: master this on the Daily first. Identify the expected direction of the next daily candle before it forms — this is described as the single biggest skill a trader can build',
        'Once daily bias is clear, combine it with intraday timing (killzones) to anticipate where the manipulation phase (Judas Swing) is likely to occur — without a clear daily bias, you cannot predict where the Judas Swing will happen',
        'Common mistake called out directly in the notes: ignoring the market narrative and HTF bias, and only looking for entries on the entry timeframe — "the entry is only a fragment"',
        'Never trade against the monthly or weekly structure, even if the daily/entry-timeframe setup looks perfect',
        'Keep HTF PD Arrays intact — do not over-fractionalize/refine them when dropping to lower timeframes',
        'Establish the Draw on Liquidity on the Weekly/Daily before anything else — top-down analysis exists to serve the DOL, not the other way around',
      ],
      visual_type: 'timeframe_cascade',
      related: ['market_structure', 'sessions_killzones', 'order_blocks', 'routine_profiling', 'draw_on_liquidity', 'dse_cisod'],
    },

    {
      id: 'intermarket_dxy',
      name: 'DXY, US10Y & Intermarket Analysis',
      category: 'Macro',
      icon: '🌐',
      status: 'built',
      description: '"DXY is the breath of my analysis." — NZT. The Dollar Index and US 10-Year Treasury Yield relationship gives you the long-term bias for every USD pair, before you ever look at a chart pattern.',
      rules: [
        'Bond prices and yields move inversely: Bond Prices Fall → Yields Go Up → Dollar Strengthens. Bond Prices Rise → Yields Go Down → Dollar Weakens',
        'If you have the direction of the US10Y, you effectively have the direction of the DXY — this is how you build your long-term bias',
        'Always analyze the DXY first. If DXY hits an Order Block, expect a reaction on EUR/USD even if the Euro chart looks unclear on its own',
        'Trade pair selection: pair a weak currency with a strong currency for dynamic movement. Weak-weak or strong-strong pairings produce consolidation',
        'BTC is inversely correlated to DXY — when DXY rises, BTC tends to fall, and vice versa. Consider DXY direction before trading crypto',
        'SMT Divergence: compare correlated markets (DXY/EURUSD/GBPUSD in forex; US30/US500/US100 in indices) — when one sweeps a liquidity level and the others don\'t, the one that swept is the manipulated asset and the preferred reversal trade',
        'Relative strength example: if EURGBP is trading higher (EUR stronger than GBP) while GBPUSD has completely filled its FVG, GBPUSD is the cleaner short — avoid the choppier EURUSD',
        'Interest Rate Differentials (IRD): capital flows toward the higher-yielding currency when monetary policies diverge — this drives the underlying cross-pair direction',
      ],
      visual_type: undefined,
      related: ['macroeconomics', 'top_down'],
    },

    {
      id: 'macroeconomics',
      name: 'Macroeconomics',
      category: 'Macro',
      icon: '🏛️',
      status: 'built',
      description: 'Interest rates are the core driving force of the forex market — currency value is directly attached to the interest rate. Combining macro bias with technical analysis is an extremely strong position.',
      rules: [
        'A national currency\'s value is strongly derived from the central bank\'s interest rate — rate rises appreciate the currency, rate cuts depreciate it',
        'GDP: total value of finished goods/services produced — a rising GDP signals a growing/appreciating economy',
        'Unemployment: appears on the calendar as Non-Farm Payroll (NFP) — the most important US employment release',
        'CPI (Consumer Price Index): measures inflation via a weighted basket of goods. Rising CPI signals the central bank may raise rates to combat inflation',
        'Monetary Policy Committee (MPC) combats inflation via two levers: interest rates and money supply (Quantitative Easing/Tapering)',
        'QE = central bank buys bonds, increasing bond demand/price, which lowers yields, which historically lowers rates and can weaken the currency over time. QT is the inverse',
        'Use the Commitment of Traders (COT) report (barchart.com → Currencies → Commitment of Traders) to see whether large funds are net long or net short — focus on "commercials"',
        'FOMC and NFP are not trading days — sit on your hands and observe how price reacts so you\'re aligned for the days after',
        'Interest rates have an inverse relationship with the stock market — rates up, stocks down, and vice versa',
      ],
      visual_type: undefined,
      related: ['intermarket_dxy', 'news_calendar'],
    },

    {
      id: 'news_calendar',
      name: 'News & Economic Calendar',
      category: 'Macro',
      icon: '📰',
      status: 'built',
      description: 'News is used as a catalyst to provide the volatility needed to reach a pre-determined PD Array or liquidity pool — not treated as a bearish/bullish signal in isolation.',
      rules: [
        'We don\'t primarily care whether news is bearish or bullish — we care about the TIME, since that tells you when the move is coming',
        'Red folder events (forexfactory.com) are the highest-impact — expect large moves. Orange/yellow folders can still swing price meaningfully',
        'Do not trade FOMC or NFP directly — they can change market state instantly. Sit on your hands and observe',
        'The candle containing a scheduled high-impact news event sweeps the previous candle\'s high or low roughly 95% of the time before the intended directional move',
        'Before a big news event, check the chart: are lows being taken out (expect bullish), or highs (expect bearish)? Is there a consolidation, and why?',
        'A Judas Swing/manipulation is often engineered specifically around a scheduled news release — the news provides the "excuse" for the algorithm',
        'NFP consistently drops the first Friday of the month, engineered at the open of the new monthly candle to create the initial manipulation phase',
        'SMC generally avoids heavy engagement during NFP week',
      ],
      visual_type: undefined,
      related: ['macroeconomics', 'cbdr_adr'],
    },

    {
      id: 'quarterly_theory',
      name: 'Quarterly Shifts & Open Float',
      category: 'Time',
      icon: '📅',
      status: 'built',
      description: 'CORRECTED from generic "IPDA" placeholder — NZT defines quarters on his own calendar, distinct from the standard financial year, used for identifying major trend moves.',
      rules: [
        'NZT\'s quarters: Q1 begins December 1st, Q2 begins March 1st, Q3 begins June 1st, Q4 begins September 1st',
        'A significant directional move typically occurs at the start of most quarters, with a retracement around the middle of the quarter',
        'Quarters often follow the PO3 (Accumulation-Manipulation-Distribution) pattern at the quarterly scale',
        'Seasonal tendency: Q1 is often an accumulation phase (holiday season). Q2 and Q3 usually contain the most significant directional moves',
        'When you see an MSS on the higher timeframe, stay out of trading until you\'ve collected enough data to understand where it\'s going',
        'Open Float: the key liquidity points in the market — observing which are being violated vs. respected is considered the best way to determine what institutional money is doing. Distinguish short-term swings from significant major turning points',
      ],
      visual_type: undefined,
      related: ['top_down', 'market_structure'],
    },

    {
      id: 'routine_profiling',
      name: 'Routine: Weekly, Daily & Monthly Profiling',
      category: 'Protocol',
      icon: '🗓️',
      status: 'built',
      description: 'The full routine framework: Weekly/Monthly Expansion → Weekly Profiling → Daily Expansion → Daily Profiling → Intraday PO3 execution. Three constant focus points at every timeframe: where price is now, where it came from, where it\'s likely to go.',
      rules: [
        'Weekly Expansion: analysis begins on the weekly (or higher). Goal — determine which direction the weekly candle\'s expansion favors, not where it will close',
        'If weekly direction is unclear, remain a spectator until clarity emerges — typically Tuesday or Wednesday',
        'Monthly is the fallback confirmation — checked once a week, biases should align (if monthly is bullish, weekly should align). Emphasis on the first two weeks of the month for the monthly Judas Swing',
        'Weekly Profiling: Sunday\'s 5PM NY Opening Price is the weekly equivalent of the Midnight Open. Bullish profile = manipulation early week (Mon/Tue) beneath Sunday Open, then expansion the rest of the week',
        'If weekly bias is wrong: adapt. Use midweek clarity (compare current price to Sunday Open). Watch for Thursday retracements toward Sunday Open — this doesn\'t necessarily mean the trend is over, it may just be a retracement day',
        'Daily Expansion: use the weekly profile to understand likely daily expansions. Let Monday play out fully before committing — it functions like an Asian Range for the week',
        'Daily Profiling (Intraday PO3): Accumulation = consolidation (Asian Range ideal) → Manipulation = the Judas Swing beneath/above the Midnight Open → Distribution = the expansion',
        'The Midnight Opening Price always stays on the chart — it is the measure of expansion. Below it = protraction; above it = expansion (bullish day)',
        'Daily checklist: mark Midnight Open, note news events, monitor Market Maker Model / PO3 unfolding around the Midnight Open framed by HTF PD Arrays',
      ],
      visual_type: undefined,
      related: ['top_down', 'ohlc_olhc', 'quarterly_theory'],
    },

    {
      id: 'dse_cisod',
      name: 'DSE Framework & CISOD',
      category: 'Protocol',
      icon: '🧭',
      status: 'built',
      description: 'NZT\'s complete decision-making framework, distilled to three components: Direction (where should price go), Stage (is the market creating the conditions for that move), and Entry (execute using one repeatable PD Array).',
      rules: [
        'Direction: everything starts with directional bias. If the current candle closed right now, where should the next candle logically seek liquidity? Only hunt setups in that direction',
        'Stage: direction tells you WHERE, stage tells you WHEN. The stage is your market model — Market Maker Buy/Sell Model, Power of Three, Accumulation, Manipulation, Stop run, Liquidity sweep, MSS. No stage = no trade',
        'A stage has two parts: (1) identify where a setup is likely to form — price at/from a minimum 1H–4H PD Array supporting your bias, or a run on a previous week/day high or low; (2) confirm a CISOD',
        'CISOD = Change In State Of price Delivery. Found on lower timeframes as the final layer of confluence before entry',
        'A valid CISOD requires: displacement + either cutting through an FVG or creating an MSS on the 15M or 5M. The 15M and 5M must be aligned — avoid trades where the timeframes contradict',
        'Priority: 4H or Daily PD Array → prioritize the 15M CISOD. 1H PD Array → the 5M CISOD is generally sufficient',
        'A displacement move is not confirmed until the candle CLOSES — do not anticipate confirmation while the candle is still forming',
        'Entry: the precise execution inside the confirmed opportunity — FVG, Order Block, Mitigation Block, OTE, or IOFED',
        'Most traders over-focus on entries. The entry is the easiest part — the real skill is recognizing the Stage',
        'Reliable swing points for anchoring: the low/high that ran stops prior to an MSS (usually the SMR of a Market Maker Model), or a swing that retraced into a supporting array and expanded away (an IOFED)',
      ],
      visual_type: undefined,
      related: ['market_maker_models', 'ote', 'draw_on_liquidity', 'top_down', 'external_internal_liquidity'],
    },

    {
      id: 'dynamic_risk_profile',
      name: 'Dynamic Risk Profile (DRP)',
      category: 'Risk',
      icon: '🛡️',
      status: 'built',
      description: 'The standard advice of a fixed 1% risk throughout an account\'s life has a flaw: it limits profit maximization when winning, and limits damage reduction when in drawdown. DRP changes risk % based on account performance and trader emotional state.',
      rules: [
        'Risk Value = (Stop-loss in pips) × (Lot size). Risk is always measured as a percentage of account equity',
        'The "Five Loss" Test: can your current risk protocol withstand 5 consecutive losses without feeling like you can\'t come back? If not, your risk % is too high',
        'DRP tiers: Drawdown/small profit (<4%) → reduce risk to 0.3–0.5%, objective is protecting capital and creeping back to breakeven',
        'Neutral (4–8%) → use neutral risk (~1%), this is the starting point',
        'Profit/on a roll (>8%) → incrementally increase risk (1.5–1.75%) to maximize gains and leverage the profit buffer',
        'Always define a level of loss where you revert to neutral risk — e.g. if 8% up you risk 1.5%; if you drop back to 4% up, revert to 1% until you climb back to 8%',
        'For funded accounts (e.g. FTMO-style): start the challenge at 0.5% risk to make hard breaches (5% daily / 10% overall) highly unlikely, requiring 10-20 consecutive losses. Build a 3-4% buffer first, THEN increase to 1%',
        'The only thing that should change across your trading career is risk applied at different account stages — your trade plan and technical approach stay constant',
      ],
      visual_type: undefined,
      related: ['realistic_expectations'],
    },

    {
      id: 'realistic_expectations',
      name: 'Realistic Expectations & Trading Psychology',
      category: 'Risk',
      icon: '🧠',
      status: 'built',
      description: 'A consistent, realistic 2:1 R:R twice a week is enough to build significant wealth over time — and far more achievable and repeatable than chasing 5:1 or 20:1 trades that look great on paper but fail in practice.',
      rules: [
        'The trading career splits into three stages: Learning (study) → Applying (demo) → Live. Do not skip or rearrange this process — two weeks on demo is not consistency',
        '2:1 R:R twice a week ≈ 4% weekly profit at 1% risk — this alone overcomes most prop firm challenges. Winning 2:1 trades consistently does wonders for morale',
        'High R:R (5:1+) looks great on paper but four consecutive losses (a realistic outcome even at high win-expectancy) opens the door to revenge trading',
        'You do not need to trade every day — Monday and Friday are often for sitting on your hands. You only need to be right once or twice a week',
        'Being right WITHOUT entering is still a win — there are two forms of being right: making money, and correctly reading the market without getting in',
        'The "Five Loss" test and Dynamic Risk Profile exist specifically to remove the fear of losing — reduce risk until you\'re not thinking about P&L, and focus purely on trade quality',
        '90% of traders lose money within 90 days — yet 90% appear to be winning on social media. Ignore the highlight reel and focus on your own process',
      ],
      visual_type: undefined,
      related: ['dynamic_risk_profile', 'backtesting_journaling'],
    },

    {
      id: 'backtesting_journaling',
      name: 'Backtesting & Journaling Method',
      category: 'Protocol',
      icon: '📓',
      status: 'built',
      description: 'Backtesting is practicing three specific skills, not "finding entries": Delivery of Price (predicting candles), Data Collection, and Pattern Recognition. Directly informs how the Apply section should be structured.',
      rules: [
        'Pattern Recognition: find 20 examples of every single array (FVG, OB, Mitigation, Rejection Block etc.) and document them visually until they "jump out at you" live',
        'Data Collection: track things like how often the day/week high forms on a given day, how often London runs the Asian range, how often an MSS occurs in NY at 8:30. Practice weekly and keep adding data points',
        'Delivery of Price: practice predicting whether the next 1-4 candles trade higher or lower given the current narrative — do this consciously for 30 days for an exponential jump in bias accuracy',
        'Grading Method (Spaced Interval Repetition): list every chapter/lesson, grade your understanding 1-10, focus backtesting time on the lowest-graded weaknesses until they become strengths',
        'Split sessions by focus: e.g. Day 1 = pattern recognition (find 2-3 examples of each array), Day 2 = data collection (test the success rate of London-to-NY OTE)',
        'Most realistic practice method: use the TradingView Replay tool, place it at a random daily point where you don\'t know the outcome, mark the Midnight Open and Asian Range, then execute your model as if live',
        'Journaling has three layers: (1) backtest results and conclusions, (2) forward-test/demo trades — bias, execution signature, time of day, SL/TP justification, (3) a private personal journal on how you FELT — connecting mistakes to the emotion that caused them',
        'Daily checklist template: HTF bias and why? Premium or discount? Did Asia consolidate? Was the protraction above/below midnight price? Did London trade into a 1H-4H array? Is there an FVG left to trade off? Can you set up an OTE in NY?',
      ],
      visual_type: undefined,
      related: ['dse_cisod', 'realistic_expectations'],
    },

  ],

  // ── INSTRUMENTS ───────────────────────────────────────────
  instruments: [
    { symbol: 'FX:EURUSD',  label: 'EUR/USD',  type: 'Forex',   icon: '💶' },
    { symbol: 'FX:GBPUSD',  label: 'GBP/USD',  type: 'Forex',   icon: '💷' },
    { symbol: 'FX:USDJPY',  label: 'USD/JPY',  type: 'Forex',   icon: '💴' },
    { symbol: 'FX:AUDUSD',  label: 'AUD/USD',  type: 'Forex',   icon: '🦘' },
    { symbol: 'FX:GBPJPY',  label: 'GBP/JPY',  type: 'Forex',   icon: '💱' },
    { symbol: 'FX:EURGBP',  label: 'EUR/GBP',  type: 'Forex',   icon: '💱' },
    { symbol: 'TVC:DXY',    label: 'DXY',      type: 'Index',   icon: '💵' },
    { symbol: 'TVC:US10Y',  label: 'US10Y',    type: 'Bond',    icon: '📜' },
    { symbol: 'CAPITALCOM:US500',  label: 'S&P 500', type: 'Index', icon: '🇺🇸' },
    { symbol: 'CAPITALCOM:US100',  label: 'NAS 100', type: 'Index', icon: '💻' },
    { symbol: 'CAPITALCOM:US30',   label: 'DOW 30',  type: 'Index', icon: '🏭' },
    { symbol: 'TVC:GOLD',    label: 'Gold',     type: 'Commodity', icon: '🥇' },
    { symbol: 'TVC:USOIL',  label: 'Crude Oil', type: 'Commodity', icon: '🛢️' },
    { symbol: 'BINANCE:BTCUSDT', label: 'BTC/USD', type: 'Crypto', icon: '₿' },
    { symbol: 'BINANCE:ETHUSDT', label: 'ETH/USD', type: 'Crypto', icon: '⟠' },
  ],

  // ── DECISION ENGINE WEIGHTS ───────────────────────────────
  engine_weights: {
    htf_bias:       { max: 20, label: 'HTF Bias Aligned' },
    killzone:       { max: 15, label: 'Killzone Active' },
    liquidity_raid: { max: 20, label: 'Liquidity Grab Confirmed' },
    mss:          { max: 15, label: 'MSS Confirmed' },
    entry_array:    { max: 15, label: 'Entry Array (OB/FVG)' },
    risk_valid:     { max: 10, label: 'Risk:Reward Valid' },
    target_clear:   { max: 5,  label: 'Target Identified' },
  },

  score_tiers: [
    { min: 85, max: 100, label: 'A+ Setup',    action: 'Execute at full size',    color: '#40b870' },
    { min: 70, max: 84,  label: 'A Setup',     action: 'Execute at reduced size', color: '#9b59ff' },
    { min: 50, max: 69,  label: 'B Setup',     action: 'Paper trade only',        color: '#ffaa00' },
    { min: 0,  max: 49,  label: 'No Trade',    action: 'Stand aside',             color: '#e05050' },
  ],
};